# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo-Server' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GCDWebServer'
  pod 'SRPinView'
  pod 'SRAirViews'
  pod 'AMap3DMap','6.7.0'
  pod 'BaiduMapKit','4.3.0'
  pod 'BMKLocationKit','1.4.0'

  target 'Demo-ServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo-ServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
